#                Итераторы и генераторы

Итераторы:
-позволяют обрабатывать элементы из структур данных по одному без избыточного использования оперативной памяти
-они выдают своё содержимое по одному элементу, а когда элементы заканчиваются, выдаётся ошибка.
-Все встроенные структуры данных в Python, которые поддерживают проход по своим элементам в цикле for (списки, словари, множества, кортежи, строки), содержат в себе итераторы и являются итерируемыми объектами. Чтобы получить итератор из структуры, используется функция iter().

# iter() - получает итератор 

In [6]:
new_list=[12,14,16]
iter_list=iter(new_list)
print(iter_list)

In [ ]:
-  iter_list — это объект с типом данных list_iterator
-  объект типа list_iterator не позволяет получать его элементы по индексам. 
Таким образом, можно сделать вывод, что итераторы не поддерживают индексацию
print(iter_list[2])
# Возникнет ошибка:
# TypeError: 'list_iterator' object is not subscriptable

# next() - которая возвращает следующий элемент из итератора

In [7]:
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))
print(next(iter_list))

12
14
16


StopIteration: 

In [ ]:
ошибка StopIteration. Она означает, что элементы в итераторе закончились и получить из него больше ничего нельзя. 

In [ ]:
итератор является «одноразовым» объектом: как только элементы в итераторе заканчиваются, он становится по сути бесполезным. 

In [9]:
users = ['admin', 'guest', 'root', 'anonymous']
enum_users=enumerate(users)
list_enum=list(enum_users)
print(list_enum)
print(enum_users)

[(0, 'admin'), (1, 'guest'), (2, 'root'), (3, 'anonymous')]


In [10]:
print(next(enum_users))
#Возникла ошибка итерации. Дело в том, что в итераторе закончились элементы в тот момент,
#как только мы получили из него список в примере выше, поэтому попытка получить из него ещё элементы вызвала ошибку.

StopIteration: 

In [ ]:
-  Итератор — это объект-перечислитель, который выдаёт следующий элемент из своих значений с помощью next() либо выбрасывает
исключение StopIteration, когда элементы заканчиваются.
-  Итерируемый объект — это объект, который может предоставить нам итератор. По его содержимому можно пройтись в цикле for. 
Встроенные итерируемые объекты — список, кортеж, строка, словарь, множество
-  Все встроенные итерируемые объекты в Python содержат внутри себя итератор. Чтобы получить его, необходимо использовать
функцию iter().
-  Когда мы создаём цикл for по итерируемому объекту (например, списку), интерпретатор на самом деле неявно обращается к его
итератору через iter() и использует функцию next(), чтобы получить следующий элемент. Когда цикл доходит до конца объекта,
for отлавливает исключение StopIteration и прекращает свою работу. Вот она — магия Python, которая скрыта от наших глаз. 
Именно так «под капотом» работает цикл for, и теперь вы обладаете этим «тайным знанием».
-  В Python можно создавать свои итераторы и прописывать в них правила выдачи элементов. Например, можно прописать, 
что выдавать элементы можно только по субботам, или изображения для обучения модели выдаются не по одному, а по 10 штук.
Для этого создаются специальные классы с определёнными возможностями (о классах мы поговорим в модуле по ООП).
Альтернативным вариантом такого подхода являются генераторы.

# Генераторы, yield()

In [ ]:
Генераторы — это объекты, которые при создании не вычисляют своё содержимое, но генерируют его в процессе работы.
Они выдают своё содержимое по определённым правилам только по запросу разработчика.

In [ ]:
Генератор объявляется как обычная функция. В теле функции описывается то, как будут генерироваться выдаваемые генератором 
объекты.
Синтаксис имеет одно очень важное отличие: вместо ключевого слова return в генераторе используется yield. 

In [21]:
def deposit(money,interest):
    interest=interest/100+1
    while True:
        money=round(money*interest,2)
        yield money
print(deposit(400000, 10))

<generator object deposit at 0x000001E0ACABAF20>


In [ ]:
Если вместо return в функции используется yield, то при вызове функция возвращает объект-генератор. 
Сама функция при этом не выполняется, пока мы не обратимся к генератору с помощью уже знакомой нам функции next().

Таким образом, генераторы действуют по принципу: «Решаем задачи по мере их поступления, пока задач нет — отдыхаем».

?
Чем же так важен yield и чем он отличается от return?

Оператор yield позволяет возвращать результат в основной блок кода и «замораживать» выполнение функции. 
Благодаря ему интерпретатор запоминает место, на котором он завершил работу с генератором, и возвращается на то же место
при повторном обращении к генератору с помощью next().

В случае с return выполнение функции завершилось бы после первой итерации while, и было возвращено значение переменной.

In [27]:
bank=deposit(1000000,10)
print(next(bank))
print(next(bank))
print(next(bank))
print(next(bank))
print(next(bank))

1100000.0
1210000.0
1331000.0
1464100.0
1610510.0


In [28]:
def deposit_years(money,interest, years):
    interest=interest/100+1
    for i in range(years):
        money=round(money*interest,2)
        yield money


In [29]:
bank2 = deposit_years(1500, 3, 2)
print(next(bank2))
print(next(bank2))
print(next(bank2))

1545.0
1591.35


StopIteration: 

In [ ]:
Дело в том, что цикл for в генераторе завершился после двух итераций, интерпретатор Python не встретил оператор yield, 
на котором можно было бы заморозить выполнение генератора, и окончательно прекратил работу генератора. 

Генераторы — это специальный вид итераторов. Это значит, что генераторы можно обрабатывать в цикле for

In [ ]:
bank3 = deposit_years(10000, 10, 3)
for money in bank3:
    print(money)
# Будет напечатано:
# 11000.0
# 12100.0
# 13310.0
Напомним, что на каждой итерации цикл for невидимо для нас вызывает функцию next(), чтобы получить следующий элемент 
из итератора (в нашем примере правильнее сказать генератора). Когда возникает ошибка StopIteration, цикл for её отлавливает 
и прекращает итерации.

In [ ]:
Все значения, которые генерирует функция deposit_years(), 
можно завернуть в список, просто обернув результат её работы в функцию list():

In [30]:
bank3=deposit_years(100,3,3)
sums=list(bank3)
print(sums)

[103.0, 106.09, 109.27]


In [ ]:
А вот с бесконечными генераторами так лучше не делать — возникнет бесконечный цикл, 
поскольку генератор не сможет остановить своё выполнение

In [37]:
def mygen():
    i=7
    print('hello')
    while i>0:
        i-=1
        yield i

In [39]:
gen = mygen()
print(gen)

<generator object mygen at 0x000001E0ACAC30B0>


In [38]:
gen = mygen()
for i in gen:
    print(i, end=' ')

hello
6 5 4 3 2 1 0 

###### задание

In [94]:
Напишите бесконечный итератор по списку.
Для этого создайте генератор с названием inf_iter, который принимает на вход список и возвращает элементы из него через yield.
Когда элементы в списке заканчиваются, генератор снова возвращает элементы из списка, начиная с нулевого.
Пример работы итератора:

l = [101, 102, 103]
gen = inf_iter(l)
for _ in range(10):
    print(next(gen))
Подсказка
В теле генератора организуйте бесконечный цикл (внутри бесконечного цикла реализуется цикл  for). 
В цикле for пройдитесь по списку и выдавайте его элементы с помощью yield. Так вы получите циклический доступ 
к элементам списка.

SyntaxError: invalid syntax (Temp/ipykernel_16596/4281623958.py, line 1)

In [9]:
def inf_iter(l):
    while True:
        for i in l:
            yield i

In [10]:
l = [101, 102, 103]
gen = inf_iter(l)
for i in range(5):
    print(next(gen))

101
102
103
101
102


###### задание

In [ ]:
Напишите генератор group_gen(n). Он должен при каждом вызове выдавать порядковый номер от 1 до n (включая n). 
После достижения n генератор должен снова возвращать номера, начиная с 1.

In [82]:
def group_gen(n):
    while True:
        for i in range(1,n+1):
            yield i
gen=group_gen(5)


In [83]:
for i in range(10):
    print(next(gen))


1
2
3
4
5
1
2
3
4
5


###### задание

In [84]:
# Квадраты чисел
def square_gen():
    for i in range(1,11):
        yield i**2
sq=square_gen()
list_sq=list(sq)
print(list_sq)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [86]:
print(next(sq))

StopIteration: 

### Сокращенное написние генератора/ Используют крYглые скобки


In [11]:
sq_gen=(i**2 for i in range(1,11))

### Получаем список из генератора

In [93]:
list_sq2=list(sq_gen)
print(list_sq2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### По аналогии с list() из генератора можно получить tuple() — кортеж и set() — множество:

In [12]:
list_sq2=tuple(sq_gen)
print(list_sq2)

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)


In [14]:
list_sq2=set(sq_gen)
print(list_sq2)

set()


##### Сокращенное написние генератора c условием

In [95]:
# Создаём генератор кубов чисел, которые делятся на 3
triple_cubes_generator = (x**3 for x in range(1,16) if x % 3 == 0)
print(type(triple_cubes_generator))
# Оборачиваем сгенерированные значения в список
print(list(triple_cubes_generator))

<class 'generator'>
[27, 216, 729, 1728, 3375]


#### создать сразу генератор списков [ ], множеств { }, кортежей tuple()

In [ ]:
Важное замечание: можно генерировать списки сразу, без необходимости применения функции list() к объекту-генератору.
    Достаточно написать выражение для генератора в квадратных скобках, а не в круглых. 
    Такая конструкция называется генератором списка:

# Создаём генератор списка кубов чисел, которые делятся на 3
triple_cubes_list = [x**3 for x in range(1,16) if x % 3 == 0]
print(type(triple_cubes_list))
print(triple_cubes_list)
# Будет напечатано:
# <class 'list'>
# [27, 216, 729, 1728, 3375]
То же самое работает и для множества — достаточно написать фигурные скобки вместо круглых. 
Такая запись будет называться генератором множества:

# Создаём генератор множества кубов чисел, которые делятся на 3
triple_cubes_set = {x**3 for x in range(1,16) if x % 3 == 0}
print(type(triple_cubes_set))
print(triple_cubes_set)
# Будет напечатано:
# <class 'set'>
# {1728, 3375, 216, 729, 27}
А вот кортеж так получить не выйдет, поскольку круглые скобки используются для создания генераторов. 
Но и эту проблему можно решить — достаточно окружить выражение для генератора функцией tuple(). 
Такая запись будет называться генератором кортежей:

triple_cubes_tuple = tuple(x**3 for x in range(1,16) if x % 3 == 0)
print(type(triple_cubes_tuple))
print(triple_cubes_tuple)
# Будет напечатано:
# <class 'tuple'>
# (27, 216, 729, 1728, 3375)

In [15]:
def root_generator(values):
    for val in values:
        if val >= 0:
            result = val ** 0.5
            yield result

In [16]:
new_root_generator = root_generator([-5, 25, 36, -25, 0])

In [20]:
print(next(new_root_generator))

StopIteration: 

# функция MAP()

In [ ]:
Теперь применим эту функцию к списку names с помощью специальной встроенной в Python функции map(). 
Она позволяет преобразовать каждый элемент итерируемого объекта по заданной функции.

Аргументы функции map():

Функция, которую необходимо применить к каждому элементу.
Итерируемый объект (например, список).
 Функция map() возвращает объект типа map.

In [ ]:
# Объявляем функцию для вычисления длины
def get_length(word):
    return len(word)
# Применяем функцию get_length к каждому элементу списка
lens = map(get_length, names)
# Проверим, что переменная lens — это объект типа map:
# Для этого воспользуемся функцией isinstance
print(isinstance(lens, map))
# Будет напечатано:
# True

In [ ]:
#Объект типа map на самом деле является разновидностью итератора, а значит можно получить его элементы,
# последовательно применяя функцию next():
    # Последовательно получаем элементы итератора map
print(next(lens))
print(next(lens))
print(next(lens))
# Будет напечатано:
# 4
# 6
# 5

In [ ]:
Кроме того, объекты итератора можно сразу занести в список, обернув результат работы функции map() в функцию list():

# Оборачиваем содержимое итератора map в список
lens_list = list(map(get_length, names))
print(lens_list)
# Будет напечатано:
# [4, 6, 5, 9, 8, 3]

In [ ]:
lens = list(map(lambda x: len(x), names))
print(lens)
# Будет напечатано:
# [4, 6, 5, 9, 8, 3]

In [21]:
#Задача
#Представьте, что пытаетесь выгрузить несколько новостей с сайта. У вас есть список путей до интересующих вас статей.
#Пример такого списка:

docs = [
    '//doc/5041434?query=data%20science',
    '//doc/5041567?query=data%20science',
    '//doc/4283670?query=data%20science',
    '//doc/3712659?query=data%20science',
    '//doc/4997267?query=data%20science',
    '//doc/4372673?query=data%20science',
    '//doc/3779060?query=data%20science',
    '//doc/3495410?query=data%20science',
    '//doc/4308832?query=data%20science',
    '//doc/4079881?query=data%20science'
]
links=list(map(lambda x: 'https://www.kommersant.ru'+ x, docs))
print(links)

['https://www.kommersant.ru//doc/5041434?query=data%20science', 'https://www.kommersant.ru//doc/5041567?query=data%20science', 'https://www.kommersant.ru//doc/4283670?query=data%20science', 'https://www.kommersant.ru//doc/3712659?query=data%20science', 'https://www.kommersant.ru//doc/4997267?query=data%20science', 'https://www.kommersant.ru//doc/4372673?query=data%20science', 'https://www.kommersant.ru//doc/3779060?query=data%20science', 'https://www.kommersant.ru//doc/3495410?query=data%20science', 'https://www.kommersant.ru//doc/4308832?query=data%20science', 'https://www.kommersant.ru//doc/4079881?query=data%20science']


# Функция filter()

In [ ]:
lens_list = [4, 6, 5, 9, 8, 3]
even_list = []
# Создаём цикл по элементам списка
for item in lens_list:
    # Проверяем условие, что текущий элемент списка чётный
    if item % 2 == 0: # Если условие выполняется,
        # добавляем элемент в новый список
        even_list .append(item)
print(even_list)
# Будет напечатано:
# [4, 6, 8]

In [ ]:
Однако эту задачу можно решить с помощью специальной встроенной в Python функции filter(). 

Она позволит отфильтровать переданный ей итерируемый объект и оставить в нём только те элементы, которые удовлетворяют условию.

Её использование аналогично применению функции map().

Аргументы функции filter():

Функция, которая должна возвращать True, если условие выполнено, иначе возвращается False.
Итератор, с которым производится действие.
Функция filter() возвращает объект типа filter

In [ ]:
# Объявляем функцию для проверки чётности числа
def is_even(num):
    if num % 2 == 0:
        return True
    return False


lens_list = [4, 6, 5, 9, 8, 3]
# Применяем функцию is_even к каждому элементу списка
even = filter(is_even, lens_list)
# Убедимся, что even — объект типа filter
print(isinstance(even, filter))
# Будет напечатано:
# True

In [ ]:
Объект filter также является итератором. Сохраним все элементы из него в список и напечатаем этот список:

print(list(even))
# Будет напечатано:
# [4, 6, 8]

In [ ]:
lens_list = [4, 6, 5, 9, 8, 3] 
# Применяем lambda-функцию к каждому элементу списка
even = filter(lambda x: x % 2 == 0, lens_list)
print(list(even))
# Будет напечатано:
# [4, 6, 8]

In [ ]:
В общем случае функция filter() может быть использована в тех случаях, когда у вас есть набор данных
(в виде итерируемого объекта) и вам необходимо отбросить элементы, 
которые не проходят по условию (оценка меньше 70 баллов, нечётные числа, «битые» картинки или другие файлы).

Тогда вы можете создать отдельную функцию, которая будет возвращать True или False в зависимости от условия. 
Применив эту функцию к данным с помощью filter(), вы оставите в своих данных только те элементы, для которых функция вернула 
True.

In [ ]:
. Необходимо написать функционал, который позволяет отфильтровать среди всех запрашиваемых пользователем услуг
(их количество произвольное) только те, которые предоставляются многодетным семьям.

Список услуг, предоставляемых многодетным семьям:

family_list = [
    'certificate of a large family',
    'social card',
    'maternity capital',
    'parking permit',
    'tax benefit',
    'reimbursement of expenses',
    "compensation for the purchase of children's goods"
    ]
Определите функцию family(), на вход которой подаётся произвольное количество аргументов (строки с названием услуг МФЦ), 
а в результате возвращается список услуг, которые могут быть оказаны только многодетной семье.

In [26]:
family_list = [
    'certificate of a large family',
    'social card',
    'maternity capital',
    'parking permit',
    'tax benefit',
    'reimbursement of expenses',
    "compensation for the purchase of children's goods"
    ]
def family(*args):
    new_list=[]
    for i in args:
        if i in family_list:
            new_list.append(i)
    return new_list

    
print(family('newborn registration', 'parking permit', 'maternity capital', 'tax benefit', 'medical policy'))

['parking permit', 'maternity capital', 'tax benefit']


In [41]:
def family(*args):
    family_list = [
    'certificate of a large family',
    'social card',
    'maternity capital',
    'parking permit',
    'tax benefit',
    'reimbursement of expenses',
    "compensation for the purchase of children's goods"
    ]
    print(*args)
    return list(filter(lambda x: x in family_list, args))
print(family('newborn registration', 'parking permit', 'maternity capital', 'tax benefit', 'medical policy'))

newborn registration parking permit maternity capital tax benefit medical policy
['parking permit', 'maternity capital', 'tax benefit']


# функция ZIP()

In [42]:
surnames = ['Ivanov', 'Smirnov', 'Kuznetsova', 'Nikitina']
names = ['Sergej', 'Ivan', 'Maria', 'Elena']
# Создаём цикл по элементам итератора zip — кортежам из фамилий и имён
for surname, name in zip(surnames, names):
    print(surname, name)

Ivanov Sergej
Smirnov Ivan
Kuznetsova Maria
Nikitina Elena


In [ ]:
Перед вами стоит задача разбить пользователей на три группы, чтобы в дальнейшем проводить А/B/C-тестирование.
Например, первой группе вы выдаёте первый вариант интерфейса вашего приложения, второй группе — второй, третьей группе — третий.
Затем вы будете сравнивать реакцию пользователей и делать вывод, какой интерфейс лучше.

Для генерации групп дан генератор group_gen. Аргументом данного генератора является число n — число групп (у нас n = 3). 
При каждом вызове  генератора он возвращает число от 1 до n. После достижения n генератор снова возвращает номера групп, 
начиная с 1.

def group_gen(n=3):
    while True:
        for i in range(1, n+1):
            yield i
Пример списка пользователей:

users = ['Smith J.', 'Petrova M.', 'Lubimov M.', 'Holov J.']
Напишите функцию print_groups, которая принимает список с именами пользователей. Используя генератор групп group_gen,
печатайте на экран:

<Фамилия И.> in group <номер группы по порядку>.

Например для списка users вывод будет таким:

Smith J. in group 1
Petrova M. in group 2
Lubimov M. in group 3
Holov J. in group 1

In [46]:
users = ['Smith J.', 'Petrova M.', 'Lubimov M.', 'Holov J.']
def group_gen(n=3):
    while True:
        for i in range(1, n+1):
            yield i
for name, group in zip(users, group_gen(n=3)):
    print (name, group)

Smith J. 1
Petrova M. 2
Lubimov M. 3
Holov J. 1


# функция reduce()

In [ ]:
reduce(), как и map() или filter(), в качестве первого аргумента принимает функцию, в качестве второго — итерируемый объект
(например, список).

reduce() выполняет следующие действия:

1Берёт первый и второй элементы из итератора, применяет к ним переданную функцию.

2Запоминает значение, которое получено в шаге 1, и подставляет его в качестве первого аргумента в функцию.
В качестве второго аргумента reduce() получает следующий элемент из генератора. 

3Действие 2 повторяется до тех пор, пока в итерируемом объекте есть элементы.

4Функция reduce() возвращает последнее значение, которое вернула функция

In [47]:
# Импортируем модуль functools
from functools import reduce

iterable = list(range(1, 6))
# Применяем lambda-функцию для вычисления к произведения к списку
reduced = reduce(lambda x,y: x*y, iterable)
print(reduced)

120


In [ ]:
Напишите функцию-декоратор-логгер logger(name).

При создании декоратора передаётся имя логгера, которое выводится при каждом запуске декорируемой функции.

Декорированная функция должна печатать:

перед запуском основной:
<имя логгера>: Function <имя декорируемой функции> started
после запуска основной:
<имя логгера>: Function <имя декорируемой функции> finished
Примечание. Узнать имя функции из переменной func, переданной в декоратор, можно с помощью конструкции func.__name__.
Это так называемые «магические» атрибуты у объектов в Python (о них мы поговорим в модуле по ООП). 
Обратите внимание, что name обрамлён двумя символами нижнего подчёркивания "_" слева и справа.

Пример работы функции:

@logger('MainLogger')
def root(val, n=2):
    res = val ** (1/n)
    return res
 
print(root(25))
# MainLogger: Function root started
# MainLogger: Function root finished
# 5.0

In [97]:
def logger(name):
    def decor(func):
        def decor_logger(*args, **kwargs):
            print(name._name_,"Function", 'started', name )
            print("Function", 'finished')
            result=func(*args, **kwargs) 
            return result
        return decor_logger
    return decor

In [98]:
@logger("tata")
def root(val, n=2):
    res = val ** (1/n)
    return res

In [99]:
print(root(4))

AttributeError: 'str' object has no attribute '_name_'

# встроенный модуль Collections 

In [1]:
#Collections позволяет упростить написание кода при решении некоторых типовых задач, таких как подсчёт числа различных элементов или создание словаря для хранения в нём списков.

# объекты из модуля Collections, такие как Counter, defaultdict, deque и OrderedDict

In [2]:
from collections import Counter
c = Counter()
c['red'] = 1
print(c)
type(c)

Counter({'red': 1})


collections.Counter

In [15]:
# Узнать сумму всех значений в объекте Counter:
from collections import Counter
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']
c = Counter(cars)
print(c.values()) #получаем элементы (число раз, когда встретился ключ) с помощью функции value
print(sum(c.values())) #Узнать сумму всех значений в объекте Counter
print(c) # посчитать сколько раз встречаются все обьекты
print(c['red']) # посчитать сколько раз встречается обьект
print(c['purple']) #Если обратиться к счётчику по несуществующему ключу, то, в отличие от словаря, ошибка KeyError не возникнет:

dict_values([3, 2, 3, 1])
9
Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})
3
0


# subtract()
### (counter_moscow.subtract(counter_spb) subtrack() вычитание с изменением первого аргумента и 
### сложение (counter_moscow + counter_spb)


In [67]:
# вычитане и ссложение словарей
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
print(counter_moscow + counter_spb)

counter_moscow.subtract(counter_spb)
print(counter_moscow)


Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [50]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
print(counter_moscow)
print(counter_moscow-counter_spb)
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'black': 2, 'yellow': 1})
Counter({'black': 4, 'yellow': 3, 'white': 2})


## .elements() получить список всех элементов(возвращает итератор в алфавитнок порядке)   #### чтобы распаковать его, нужен *
## list() возвращает неповторяющикеся элементы
## .most_common() самые частые элементы в порядке убывания в виде кортежа
## .clear() очистить счетчик

In [54]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)

print(list(counter_moscow.elements()))
print(*counter_moscow.elements())



['black', 'black', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'yellow']
black black black black white white yellow yellow yellow


In [55]:
print(list(counter_moscow))
print(dict(counter_moscow))
print(counter_moscow.most_common())
print(counter_moscow.most_common(2)) #  в скобкаж количество первых эелемнтов кортежа
print(counter_moscow.clear())

['black', 'white', 'yellow']
{'black': 4, 'white': 2, 'yellow': 3}
[('black', 4), ('yellow', 3), ('white', 2)]
[('black', 4), ('yellow', 3)]
None


# defaultdict()
#### позволяет задавать тот тип данных, который хранится в словаре по умолчанию (в нашем случае это должен быть список). Это бывает удобно в том случае, если приходится заполнять одну и ту же структуру данных, экземпляр которой должен храниться по каждому ключу в словаре. Обратите внимание, что в скобках мы передаём именно указатель на класс объекта (например list; также можно было бы применить set, dict) без круглых скобок, которые используются для создания нового экземпляра объекта.

In [84]:
# Обычный способ
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
groups = {}

for student, group in students:
    if group not in groups:
        groups[group]=list()
    groups[group].append(student)
print(groups)

# defaultdict


{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}


In [23]:
from collections import defaultdict
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

groups = defaultdict(list)

for student, group in students:
    groups[group].append(student)
print(groups)
print(groups[2021]) #Теперь в словаре groups автоматически появился элемент 2021 с пустым списком внутри, несмотря на то что мы его не создавали:
print(groups)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})
[]
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})


# OrderedDict()  
### Специальный словарь, который гарантирует сохранение ключей в порядке их добавления

In [89]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
from collections import OrderedDict
ordered_dict_data = OrderedDict(data)
print(ordered_dict_data)

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [94]:
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)
ordered_client_ages['Ola']=1  # добавляем элемент и он оказывется в конце
print(ordered_client_ages)
del ordered_client_ages['Ola']   # удалить элемент
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Ola', 1)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])


In [65]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
         
# Отсортируйте список ratings по убыванию рейтинга. Для кафе
# с одинаковым рейтингом отсортируйте кортежи по названию.

from collections import OrderedDict

ratings_dict=OrderedDict(sorted(ratings, key = lambda x: (-x[1],x[0])))
print(ratings_dict)


OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])


# deque
#### append (добавить элемент в конец дека);
#### appendleft (добавить элемент в начало дека);
#### pop (удалить и вернуть элемент из конца дека);
#### popleft (удалить и вернуть элемент из начала дека).

In [119]:
from collections import deque
dq = deque()
dq.append('Ivanov')
dq.append('Petrov')
dq.append('Smirnov')
print(dq)
dq.appendleft('Leva')
print(dq)
dq.append('pra')
dq.append('ppopo')
dq.popleft()
del dq[2]  # удалили по индексу
dq

deque(['Ivanov', 'Petrov', 'Smirnov'])
deque(['Leva', 'Ivanov', 'Petrov', 'Smirnov'])


deque(['Ivanov', 'Petrov', 'pra', 'ppopo'])

### extend() extendleft() - добавить сразу несколько

In [105]:
# В скобках передаём список при создании deque,чтобы сразу добавить все его элементы в очередь
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [106]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)

deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


### maxlen() установить очередь с ограниченой максимальной длиной

In [107]:
limited = deque(maxlen=3)
print(limited)

deque([], maxlen=3)


In [109]:
first_q = deque([1,2,3,4,5,6], maxlen=3)
first_q.append(8)
first_q

deque([5, 6, 8], maxlen=3)

In [114]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]
import numpy as np
day = deque(maxlen=7)
for temp in temps:
    day.append(temp)
    if len(day)>=6:
        middle_temp=round(np.mean(day), 2)
        print(middle_temp, end=';')

20.43;20.77;21.27;22.16;23.3;24.44;24.94;25.56;26.2;25.97;25.94;25.57;25.1;24.81;24.21;23.23;22.57;21.41;20.4;19.6;19.1;19.04;18.96;19.44;20.01;20.67;

### reverse() переворачивает список
### rotate(8) или rotate(-3) переносит столько значений с одного конца в другой

In [122]:
from collections import deque
list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.reverse()
dq
#deque([5, 4, 3, 2, 1])

deque([5, 4, 3, 2, 1])

In [126]:
list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.rotate(2)
print(dq) #deque([4, 5, 1, 2, 3])

list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.rotate(-2)
print(dq) #deque([3, 4, 5, 1, 2])

deque([4, 5, 1, 2, 3])
deque([3, 4, 5, 1, 2])


### Функция index позволяет найти первый индекс искомого элемента, а count позволяет подсчитать, сколько раз элемент встретился в очереди(функции аналогичны одноимённым функциям для списков)/ при попытке узнать индекс несуществующего элемента возникнет ValueError/ посчитать несуществующий элемент можно (получится просто 0):

In [130]:
list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.index(5)

4

In [131]:
list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.count(1)

1

### .clear()

In [133]:
list_1 = [1,2,3,4,5]
dq = deque(list_1)
dq.clear()
dq

deque([])

In [138]:
a = [('asd', 2)]
b = dict(a)
b

{'asd': 2}

In [145]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

st_dict = defaultdict(list)
from collections import defaultdict
for numer, name in students:
    st_dict[name].append(numer)
print(st_dict)

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [25]:
#Необходимо напечатать словарь, в котором ключи — годы, а значения — показатели температуры. Ключи необходимо отсортировать в порядке убывания соответствующих им температур.
from collections import OrderedDict
temps =  [('2004', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]
t = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))
t


OrderedDict([('2001', -2.5), ('2004', -4.4), ('2002', -4.4), ('2003', -9.5)])

In [129]:
#Напишите функцию brackets(line), которая определяет, является ли последовательность из круглых скобок правильной.
from collections import deque

def brackets(line):
    dq = deque()
    
    for symb in line:
        if symb == "(":
            dq.append(symb)
            print(dq)
        elif symb == ")":
            if "(" in dq:
                dq.pop()
                print(dq)
            else:
                dq.append(symb)
                print(dq)
    if len(dq)==0:
        return True
    else:
        return False
            
        
        

In [130]:
print(brackets(")"))


deque([')'])
False


In [42]:
a=''
b=[]
for i in a:
    print (i)
    b.append(i)
    print(b)
    

In [63]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
          ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
          ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]
# Отсортируйте список ratings по убыванию рейтинга. Для кафе
# с одинаковым рейтингом отсортируйте кортежи по названию.
ratings.sort(key=lambda x: (-x[1], x[0]))
print(ratings)

[('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)]


In [127]:
#Напишите функцию task_manager, которая принимает список задач для нескольких серверов. Каждый элемент списка состоит из кортежа (<номер задачи>, <название сервера>, <высокий приоритет задачb
# Функция должна создавать словарь и заполнять его задачами по следующему принципу: название сервера — ключ, по которому хранится очередь задач для конкретного сервера. 
# #Если поступает задача без высокого приоритета (последний элемент кортежа — False), добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.

#Для словаря используйте defaultdict, для очереди — deque.

#Функция возвращает полученный словарь с задачами.

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]
 
def task_manager(tasks):
    from collections import deque
    from collections import defaultdict
    
    tasks_manager_dict = defaultdict(deque)
    
    for i in tasks:
        if i[2]:
                tasks_manager_dict[i[1]].appendleft(i[0])
        else:
                tasks_manager_dict[i[1]].append(i[0])   
            
    
    return tasks_manager_dict
task_manager(tasks)

defaultdict(collections.deque,
            {'office': deque([36871, 40690, 33850]),
             'voltage': deque([41667, 35364])})

# ___________________________________numpy

In [135]:
import numpy as np
a = np.int64(25)
print(a)
np.iinfo(np.int64)

25


iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [137]:
#В NumPy доступны и беззнаковые целочисленные типы данных. Они имеют корень uint (unsigned int — беззнаковое целое). uint доступны также с выделением памяти в 8, 16, 32 и 64 бита.
# При этом максимально возможное число оказывается в два раза больше, чем для соответствующего int, поскольку отрицательные числа исключены из типа данных uint.
a = np.uint8(2)
a
np.iinfo(a)

iinfo(min=0, max=255, dtype=uint8)

In [144]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))

2147483610 2147483605
4294967215


In [146]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [ ]:
# Следует обратить внимание на типы данных bool_ и str_.
# Они аналогичны bool и str из встроенных в Python, однако записывать их необходимо именно с нижним подчёркиванием, иначе произойдёт приведение к стандартному типу данных, а не типу NumPy.
# В целом, существенной разницы между этими типами данных нет, однако о такой двойственности следует помнить при сравнении типов переменных: 
# тип bool не является эквивалентным numpy.bool_, несмотря на то что оба типа данных хранят значения True или False.

In [157]:
#Полный список (а точнее, словарь) типов данных в NumPy можно получить с помощью атрибута sctypeDict. 
#Вывод не приводится, поскольку в этом словаре содержится более 100 ключей (их число может варьироваться в зависимости от версии NumPy)!
#Однако основные названия типов данных в NumPy не меняются от версии к версии.
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


### np.array(<объект>)

In [2]:
#Создать массив из списка можно с помощью функции np.array(<объект>):
import numpy as np
np_arr = np.array([1,2,3,4])
np_arr

array([1, 2, 3, 4])

In [4]:
np_arr.dtype

dtype('int32')

In [12]:
# указываем тип данных самостоятельно
arr = np.array([1,2,3,4], dtype=np.int64) 
#array([1, 2, 3, 4], dtype=int64)

In [11]:
# преобразовать массив в другой тип данных
arr = np.float32(arr) 
#array([1., 2., 3., 4.], dtype=float32)

In [15]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

### .ndim

In [17]:
#знать размерность массива можно с помощью .ndim
arr.ndim #1 Одномерный
nd_arr.ndim #2 двумерный

2

### .size

In [19]:
#Узнать общее число элементов в массиве можно с помощью .size:
arr.size
nd_arr.size

9

### .shape

In [23]:
#Форма или структура массива хранится в атрибуте .shape: вывод представлен кортежем (если выходит одно число, то ставится запятая для кортежа)
print(nd_arr.shape)
print(arr.shape)

(3, 3)
(5,)


In [24]:
#Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [28]:
arr=np.array([1, 1])
print(arr.itemsize)

4


### np.zeros()

In [9]:
# Массив из нулей создаётся функцией np.zeros. 
# Она принимает аргументы shape (обязательный) — форма массива (одно число или кортеж) и dtype (необязательный) — тип данных, который будет храниться в массиве.
arr=np.zeros((5,3,2))
arr=np.zeros(3, dtype=np.int8)
arr

array([0, 0, 0], dtype=int8)

### arange([start,] stop, [step,], dtype=None)

In [11]:
# Ещё одной удобной функцией для создания одномерных массивов является arange. Она аналогична встроенной функции range, но обладает рядом особенностей. 
# Вот её сигнатура: arange([start,] stop, [step,], dtype=None).

# Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:

# start (входит в диапазон возвращаемых значений) задаёт начальное число;
# stop (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
#  step задаёт шаг, с которым в массив добавляются новые значения.
#  В отличие от range, в функции arange все перечисленные параметры могут иметь тип float.

arr = np.arange(1,8,2,dtype=np.float16)
arr

array([1., 3., 5., 7.], dtype=float16)

### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [ ]:
#На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. 
#Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство).
#Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

# start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
# num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
# endpoint — включён или исключён конец диапазона (по умолчанию включён);
# retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
# dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).
# Функцию linspace очень удобно использовать при построении графиков различных функций, поскольку она позволяет получить равномерный массив чисел, 
# к которому можно применить исследуемую функцию и показать результат на графике. 
# Вы научитесь это делать в модуле, посвящённом визуализации.

In [12]:
arr = np.linspace(1, 10, num=5, endpoint=True, retstep=True, dtype=np.float16 )
arr

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ], dtype=float16), 2.25)

In [14]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True) #можно так определить шаг и вывести его
print(step)

0.1111111111111111


In [18]:
# С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно?
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True )
step.round(2)

0.46

In [48]:
# Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой: 
# первое число задало число строк, а второе — число столбцов.
# Присвоение нового значения атрибуту shape изменяет тот массив, с которым производится действие.

arr = np.arange(8)  #array([0, 1, 2, 3, 4, 5, 6, 7])
arr.shape = (2, 4)    # array([[0, 1, 2, 3],
#                             [4, 5, 6, 7]])

# Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. 
# Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

arr = np.arange(8)          #array([0, 1, 2, 3, 4, 5, 6, 7])
arr_new = arr.reshape(2, 4) #array([[0, 1, 2, 3],
 #                                  [4, 5, 6, 7]])
 
 #У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы.
 # Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:

arr = np.arange(8) #array([0, 1, 2, 3, 4, 5, 6, 7])
arr_new = arr.reshape (2,4, order='F') #array([[0, 2, 4, 6],
   #                                           [1, 3, 5, 7]])
   
# Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. 
# Эта операция меняет строки и столбцы массива местами. В NumPy эту операцию совершает функция transpose.

arr = np.arange(8) #array([0, 1, 2, 3, 4, 5, 6, 7])
arr.shape = (2,4)
arr_trans = arr.transpose()  #array([[0, 4],
 #                                  [1, 5],
 #                                  [2, 6],
 #                                  [3, 7]])
 
#При транспонировании одномерного массива его форма не меняется:
arr = np.array([1,2,3])
arr_tr=arr.transpose()
arr_tr

array([1, 2, 3])

In [83]:
arr = np.linspace(1,10, num=10, endpoint=True, dtype=np.int16)
print(arr)
arr[1:6]

arr_new = arr.reshape(2,5) #[ 1  2  3  4  5  6  7  8  9 10]
print(arr_new)#  [[ 1  2  3  4  5]
 #                [ 6  7  8  9 10]]
arr_new[1,1]    # 7
arr_new[:2,2]    # array([3, 8], dtype=int16)    Несмотря на то что в массиве этот срез является столбцом, вместо него мы получили одномерный массив в виде строки.
arr_new[:2,2:]   #array([[ 3,  4,  5],          Можно применять срезы сразу и к строкам, и к столбцам:
  #                      [ 8,  9, 10]], dtype=int16)
arr_new[:,1]     #array([2, 7], dtype=int16) Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие
arr_new[:2] #Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int16)

In [53]:
# СОртировка массивов новый=np.sort(массив старый) - сохраняем в новую переменную или arr.sort(массив) сразу меняет эту переменную
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)
arr = np.array([23,12,45,12,23,4,15,3])
arr.sort()
print(arr)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]
[ 3  4 12 12 15 23 23 45]


## объект nan

In [65]:
# Работа с пропущенными данными
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots         #C:\Users\tanya\AppData\Local\Temp\ipykernel_4604\786165503.py:3: RuntimeWarning: invalid value encountered in sqrt
               #roots = np.sqrt(data)
               #array([2.        , 3.        ,        nan, 1.73205081])
# объект nan. Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, но имеет несколько отличий:
np.isnan(roots) #array([False, False,  True, False])   Определили пропущенные числа с помощью 
roots[np.isnan(roots)] # array([nan])
roots[np.isnan(roots)] = 0 #Этим элементам можно присвоить новые значения, например 0
roots #array([2.        , 3.        , 0.        , 1.73205081])
sum(roots) #6.732050807568877
#Ранее проблема при подсчёте суммы элементов в массиве roots возникала из-за того, что отсутствовало значение для квадратного корня из -4 — вместо него было указано np.nan.
# #Сумма элементов массива, содержащего nan, также является nan. Поэтому приходится заменить nan, например, на 0, чтобы подсчитать сумму элементов массива.

6.732050807568877

In [71]:
data = np.array([4, 9, -4, 3, -4])
roots=np.sqrt(data)
np.isnan(roots)
len(roots[np.isnan(roots)])

C:\Users\tanya\AppData\Local\Temp\ipykernel_4604\1242385928.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots=np.sqrt(data)


2

In [82]:
arr = np.arange(15)
arr.shape=(5,3)
s= arr[: , 1]
print(arr)
s

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 1,  4,  7, 10, 13])

### векторы

In [89]:
#С векторами в NumPy можно производить арифметические операции: складывать, вычитать, умножать друг на друга, возводить один вектор в степень другого и т. д.

#Операция, применённая к двум векторам, на самом деле применяется поэлементно. 
#То есть при сложении двух векторов первым элементом нового вектора будет сумма первых элементов исходных векторов, вторым — сумма вторых элементов и т. д.
# векторы должны быть одинаковой длины
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
vec1 * vec2
vec1**2
vec1 +10
vec1 > vec2 #array([False, False,  True, False])
vec1>=10   #array([False, False, False, False])

array([False, False, False, False])

### np.linalg.norm(vec)-длина вектора   
### np.linalg.norm(vec1-vec2) - расстояние   
### np.dot(vec1,vec2)- скалярное произведение

In [99]:
         # -ДЛИНА ВЕКТОРА, то есть расстояние между его началом и концом
# возведём все элементы в квадрат, посчитаем их сумму, а затем найдём квадратный корень.
vec =np.array([3,4])
leght = np.sqrt(np.sum(vec**2))
#В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.
#Для вычисления длины вектора нам потребуется функция norm:
leght = np.linalg.norm(vec)


         # -РАССТОЯНИЕ между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] - квадратный корень из суммы квадратов разностей соответствующих координат
#  расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
#np.linalg.norm:
distance = np.linalg.norm(vec1-vec2) #12.206555615733702


        #- СКАЛЯРНЫМ ПРОИЗВЕДЕНИЕМ двух векторов называют сумму произведений их соответствующих координат
#Реализуем это в коде (по-английски скалярное произведение называют dot — точечный — или scalar product, отсюда и такое название переменной):
vec1 = np.arange(1,6)
vec2 = np.linspace(10,20,5)
scalar_product = np.sum(vec1*vec2)  # скаляр scalar_product #250.0
#np.dot(vec1,vec2)
scalar_product = np.dot(vec1,vec2) #scalar_product # 250.0
#Скалярное произведение также имеет широкое применение в математике и других операциях с векторами.
# В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:
x = np.array([25, 0])
y = np.array([0, 25])
np.dot(x,y) #0
#В целом, скалярное произведение часто используется для определения угла между векторами.

#Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
#Функция mean позволяет посчитать среднее значение. Больше не требуется реализовывать её «руками»!

0

# Случайные числа в numpy

## генерация случайных чисел float:  
### np.random.rand()

In [12]:
import numpy as np

np.random.rand() #- генерирует число  от -1 до 0
   # 0.14754490458977765
   
np.random.rand(5) #- генерирует  одномерный массив с числами от -1 до 0
   # array([0.92621206, 0.1446589 , 0.91416133, 0.9685235 , 0.73592253])
   
np.random.rand(2,2) #- генерирует  двумерный массив с числами от -1 до 0  и другие многомерные массивы
    #array([[0.84581304, 0.96970958],
    #        [0.02105096, 0.73303506]])
       
#Чтобы получить случайное число в диапазоне, например, от 0 до 100, достаточно просто умножить генерируемое число на 100:
np.random.rand(2)*100 
    #array([28.80311488, 53.62656652])

array([39.51020646, 90.2788395 ])

### np.random.sample(кортеж)

In [14]:
# функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки.

shape = (2,3)
np.random.sample(shape)
#  array([[0.65949399, 0.99947583, 0.61330769],
#       [0.62926994, 0.41182219, 0.64025097]])

# либо распаковать кортеж (*):
np.random.rand(*shape)

array([[0.46290798, 0.12540975, 0.98694689],
       [0.75380038, 0.49191887, 0.51098236]])

### np.random.uniform(low=0.0, high=0.0, size=None )

In [20]:
#Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число).
# Форма массива задаётся кортежем или одним числом.

np.random.uniform(1,10, size=5)
np.random.uniform(1,10, size=shape)
np.random.uniform(1,10, size=(5,3))

np.random.uniform() # можно без аргументов. Выдаст одно число

0.17142832333567004

## генерация случайных чисел int:  
### np.random.randint(low, high=None, size=None, dtype=int)

In [23]:
np.random.randint(8) #- нужен один обязательный аргумент
# 3
# Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

# Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
# Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
# size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
# dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

3

# Работа со случайными величинами из существующих уже данных:
### np.random.shuffle() - перемешивает значения в массиве, меняет старый массив, не выводт его (None)


In [47]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
print(np.random.shuffle(playlist)) #Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.
print(playlist)

None
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


### np.random.permutation() - перемешивает массив и сохраняет его в новую переменную, сам массив не  изменяет. Может принмать массив или список (И превращает его в массив) или число

In [44]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(playlist)
print(shuffled)

['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']
['ACDC' 'The Beatles' 'Deep Purple' 'Pink Floyd']


In [38]:
np.random.permutation(10) #создает arange(10) и перемешивает его

array([5, 4, 7, 9, 2, 3, 1, 8, 0, 6])

### np.random.choice(a, size=None, replace=True) выбрать из массива случайные числа

In [127]:
# a — одномерный массив или число для генерации arange(a);
# size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
# replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
np.random.choice(workers, size=2, replace=False)
# array(['Nikita', 'Maria'], dtype='<U6')

np.random.choice([1,2,3,4,5], size=3)

# array([4, 1, 4])
np.random.choice(10, size=(2,2), replace=False)


array([[5, 6],
       [1, 4]])

# np.random.seed(число) - генератор псевдослучайных чисел

In [52]:
np.random.seed(23)
print(np.random.randint(10, size=6))
print(np.random.randint(10, size=6))

[3 6 8 9 6 8]
[7 9 3 6 1 2]


In [86]:
#Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. Пользователю может настолько понравиться перемешанная версия плейлиста,
# что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

# Для этого напишите функцию shuffle_seed(<array>),  которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) 
# и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

def shuffle_seed(array):

    num = np.random.randint(0, (2**32-1), dtype=np.int64)
    np.random.seed(num)
    permut = np.random.permutation(array)
    return permut, num

array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([3, 2, 1, 4, 5]), 1714602883)

In [6]:
# Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

#Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.



# (5.196152422706632, 10.392304845413264)

def min_max_dist(*vec):
    vectors = []
    over_vec=[]
    for i in vec:
        vectors.append(i)  # список со всеми векторами
         
    for num in range(len(vectors)):
             
        over_vec.extend((list(map(lambda x: np.linalg.norm(vectors[num]-x), vectors))))
        print(over_vec)
    over_vec=list(set(over_vec))
    over_vec.pop(0)
    print(over_vec)
    return np.min(over_vec), np.max(over_vec)


            
import numpy as np
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([6, 8, 9])
min_max_dist(vec1, vec2, vec3)

[0.0, 5.196152422706632, 9.848857801796104]
[0.0, 5.196152422706632, 9.848857801796104, 5.196152422706632, 0.0, 4.69041575982343]
[0.0, 5.196152422706632, 9.848857801796104, 5.196152422706632, 0.0, 4.69041575982343, 9.848857801796104, 4.69041575982343, 0.0]
[9.848857801796104, 4.69041575982343, 5.196152422706632]


(4.69041575982343, 9.848857801796104)

In [227]:
def min_max_dist(*vectors):
    dists = list()
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            dists.append(np.linalg.norm(vectors[i] - vectors[j]))
        print(dists)
    return (min(dists), max(dists))

In [61]:
#Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.
#Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.
#Пример:

def any_normal(*vec):
    import numpy as np
    for i in range(len(vec)):
        for j in range(i+1, len(vec)):
            
            if np.dot(vec[i],vec[j])==0:
                return True
            else:
                return False 
            
import numpy as np
vec1 = np.array([1, 0])
vec2 = np.array([0, 1])
vec3 = np.array([3,4])
vec4 = np.array([2, 6])
vec6 = np.array([-1, 7])
vec7 = np.array([3,9])
print(any_normal(vec1, vec2, vec3))
# True



True


In [69]:
#Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.
#Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
#Функция возвращает полученный массив.
def get_loto(num: int):
    """Функция гегерирует трехмерный массив со сторонами 5х5 для игры в лото

    Args:
        num (int): принимает размер массива

    Returns:
        array: массив
    """
    loto_array = np.random.randint(1, 101, size = (num, 5, 5))
    return loto_array
get_loto(3)

array([[[70, 41, 80, 15, 71],
        [12, 64, 21, 83, 77],
        [43, 61, 17, 94, 48],
        [48, 52, 17, 51, 22],
        [79, 40, 48, 53, 73]],

       [[73, 25, 57, 97, 65],
        [63, 93, 85,  9, 67],
        [50, 92, 96, 48, 40],
        [83, 27, 15, 49, 84],
        [18, 73, 34, 68, 33]],

       [[61, 65, 21, 33, 73],
        [ 4, 68, 61, 31, 97],
        [61, 78, 27,  2, 17],
        [56, 54, 93, 77, 80],
        [68, 56, 41, 27, 56]]])

In [19]:
#Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.
#Функция также должна возвращать массив формы num x 5 x 5.
# 
# 
def get_unique_loto(num: int):
    
    """Функция гегерирует трехмерный массив со сторонами 5х5 для игры в лото без повторений

    Args:
        num (int): принимает размер массива

    Returns:
        array: массив
    """

    import numpy as np
    np.random.seed(3)
    sample =np.random.randint(1,101)
    loto_array=(np.random.choice(sample, size = (5, 5), replace=False))
    
    for i in range(num-1):
        new_loto_array=(np.random.choice(sample, size = (5, 5), replace=False))
        
        loto_array=np.concatenate((loto_array, new_loto_array))

    loto_array.shape= (num,5,5)   
    return loto_array

get_unique_loto(3)



array([[[18, 17, 12, 24, 15],
        [16, 13,  2,  1, 23],
        [14,  4, 22,  6,  7],
        [ 5, 20,  9, 11, 10],
        [19, 21,  0,  8,  3]],

       [[ 3,  9, 24,  2, 15],
        [22, 21,  6, 18, 12],
        [13, 16,  4, 23,  0],
        [17, 20, 11,  7, 10],
        [ 1, 14,  8,  5, 19]],

       [[21,  6, 18, 22,  8],
        [13, 23,  2,  9, 19],
        [15,  0, 16,  3,  4],
        [12, 11, 10, 20, 17],
        [ 1, 14, 24,  7,  5]]])

261.5